services:
  postgres:
    image: postgres:17

    env_file:
      - .env

    ports:
      - "5433:5432"

    volumes:
      - vault_ledger_data:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5


  vault_ledger_api:
    build: .

    ports:
      - "8081:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      TZ: UTC

    depends_on:
      postgres:
        condition: service_healthy


volumes:
  vault_ledger_data: